version: "3.7"
services:
  tester-gateway:
    image: tticc/tester:tester-gateway
    container_name: tester-gateway
    env_file:
      - env/tester-cluster.env
    networks:
      - "rnet"
    ports:
      - "8002:8002"
#    restart: always

  tester-gateway1:
    image: tticc/tester:tester-gateway
    container_name: tester-gateway1
    env_file:
      - env/tester-cluster.env
    networks:
      - "rnet"
#    restart: always


  tester-async:
    container_name: tester-async
    image: tticc/tester:tester-async
    env_file:
      - env/tester-cluster.env
    networks:
      - "rnet"
#    restart: always
    deploy:
      mode: replicated
      replicas: 1

  tester-webapp:
    image: tticc/tester:tester-webapp
    container_name: tester-webapp
    env_file:
      - env/tester-cluster.env
    networks:
      - "rnet"
    ports:
      - "8004:8004"
#    restart: always




networks:
  rnet:
    driver: bridge
    external: true
