server:
  port: 8004
spring:
  profiles:
    active: dev
  application:
    name: tester-web-app
  servlet:
    multipart:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
#    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
#    content-type: text/html


#mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    # 自动匹配字段驼峰规则
    map-underscore-to-camel-case: true




