version: "3.7"
services:
  rocketmq-dashboard-18:
    container_name: rocketmq-dashboard-18
    image: tticc/third:rocketmq-dashboard-18
    ports:
      - "8080:8080"
    environment:
      - NAMESRV_ADDR=nameserver1:9876@nameserver2:9876
      - SERVER_PORT=8080
    networks:
      - "rnet"
    depends_on:
      - nameserver1
      - nameserver2
  nameserver1:
    container_name: nameserver1
    image: tticc/third:rocketmq4.5-namesrv
    #    volumes:
    #      - C:/Users/18883/IdeaProjects/test-parent/tester-docker/redis/config/master:/usr/local/redis-6.0.16/out_config
    #    ports:
    #      - "8888:6379"
    networks:
      - "rnet"

  nameserver2:
    container_name: nameserver2
    image: tticc/third:rocketmq4.5-namesrv
    #    volumes:
    #      - C:/Users/18883/IdeaProjects/test-parent/tester-docker/redis/config/master:/usr/local/mq_out_config
    #    ports:
    #      - "8888:6379"
    networks:
      - "rnet"

  1-broker-a:
    image: tticc/third:rocketmq4.5-broker
    volumes:
      - E:/Development/Projects_backup/test-parent/tester-docker/rocketmq/broker/CVCluster1:/usr/local/mq_out_config
    environment:
      - BROKER_CONF=mq_out_config/broker-a.properties
      - NAME_SRV=nameserver1:9876;nameserver2:9876
    networks:
      - "rnet"
    depends_on:
      - nameserver1
      - nameserver2

  1-broker-a-s:
    image: tticc/third:rocketmq4.5-broker
    volumes:
      - E:/Development/Projects_backup/test-parent/tester-docker/rocketmq/broker/CVCluster1:/usr/local/mq_out_config
    environment:
      - BROKER_CONF=mq_out_config/broker-a-s.properties
      - NAME_SRV=nameserver1:9876;nameserver2:9876
    networks:
      - "rnet"
    depends_on:
      - nameserver1
      - nameserver2


  1-broker-b:
    image: tticc/third:rocketmq4.5-broker
    volumes:
      - E:/Development/Projects_backup/test-parent/tester-docker/rocketmq/broker/CVCluster1:/usr/local/mq_out_config
    environment:
      - BROKER_CONF=mq_out_config/broker-b.properties
      - NAME_SRV=nameserver1:9876;nameserver2:9876
    networks:
      - "rnet"
    depends_on:
      - nameserver1
      - nameserver2

  1-broker-b-s:
    image: tticc/third:rocketmq4.5-broker
    volumes:
      - E:/Development/Projects_backup/test-parent/tester-docker/rocketmq/broker/CVCluster1:/usr/local/mq_out_config
    environment:
      - BROKER_CONF=mq_out_config/broker-b-s.properties
      - NAME_SRV=nameserver1:9876;nameserver2:9876
    networks:
      - "rnet"
    depends_on:
      - nameserver1
      - nameserver2


networks:
  rnet:
    driver: bridge
    external: true
