version: "3.7"
services:
  nacos:
    #指定容器中的主机名
    hostname: nacos
    container_name: nacos
    image: nacos/nacos-server:2.0.3
    env_file:
      - env/nacos-mysql.env
    volumes:
      - ./cluster-logs/nacos:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    networks:
      - "rnet"
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"

  nacos1:
    #指定容器中的主机名
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:2.0.3
    env_file:
      - env/nacos-mysql.env
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    networks:
      - "rnet"
#    ports:
#      - "8849:8848"
#      - "9849:9848"

  nacos2:
    #指定容器中的主机名
    hostname: nacos2
    container_name: nacos2
    image: nacos/nacos-server:2.0.3
    env_file:
      - env/nacos-mysql.env
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    networks:
      - "rnet"
#    ports:
#      - "8850:8848"
#      - "9850:9848"

  nginx:
    container_name: nacos_ng
    image: nginx:1.21.6-alpine
    volumes:
      - E:/Development/Projects_backup/test-parent/tester-docker/nacos/nginx/conf:/etc/nginx/conf.d
    networks:
      - "rnet"
    ports:
      - "8849:8849"
    depends_on:
      - nacos
      - nacos1
      - nacos2

networks:
  rnet:
    driver: bridge
    external: true
