version: "3.7"
services:
  mysql_master:
    container_name: mysql_master
    image: mysql:5.7.38
    #    ports:
    #      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MASTER_SYNC_USER="root"
      - MASTER_SYNC_PASSWORD="123456"
      - ALLOW_HOST="%.%.%.%"
    volumes:
      - E:/Development/Projects_backup/test-parent/tester-docker/mysql/conf/master_conf.d:/etc/mysql/conf.d
      - master_data0:/var/lib/mysql
    networks:
      - "rnet"
    command:
      -  "--server-id=1"
      -  "--character-set-server=utf8mb4"
      -  "--collation-server=utf8mb4_unicode_ci"
      -  "--log-bin=mysql-bin"
      -  "--sync_binlog=1"

  mysql_slave1:
    image: mysql:5.7.38
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - SLAVE_SYNC_USER="root"
      - SLAVE_SYNC_PASSWORD="123456"
      - MASTER_HOST="mysql_master"
    volumes:
# slave1_conf 与 slave1_conf 里面文件的区别只有mysql.cnf里的 server-id 不一样
      - E:/Development/Projects_backup/test-parent/tester-docker/mysql/conf/slave1_conf.d:/etc/mysql/conf.d
      - slave_data1:/var/lib/mysql
    networks:
      - "rnet"
    command:
      -  "--server-id=2"
      -  "--character-set-server=utf8mb4"
      -  "--collation-server=utf8mb4_unicode_ci"
    depends_on:
      - mysql_master

  mysql_slave2:
    image: mysql:5.7.38
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - SLAVE_SYNC_USER="root"
      - SLAVE_SYNC_PASSWORD="123456"
      - MASTER_HOST="mysql_master"
    volumes:
      - E:/Development/Projects_backup/test-parent/tester-docker/mysql/conf/slave2_conf.d:/etc/mysql/conf.d
      - slave_data2:/var/lib/mysql
    networks:
      - "rnet"
    command:
      -  "--server-id=3"
      -  "--character-set-server=utf8mb4"
      -  "--collation-server=utf8mb4_unicode_ci"
    depends_on:
      - mysql_master



volumes:
  master_data0:
    driver: local
  slave_data1:
    driver: local
  slave_data2:
    driver: local


networks:
  rnet:
    driver: bridge
    external: true
