version: "3.7"

# 有问题，TSL问题导致无法启动
services:
  es001:
    image: elasticsearch:8.2.0
    container_name: es001
    environment:
      - node.name=es001
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es001,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - "rnet"
  es02:
    image: elasticsearch:8.2.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es001,es03
      - cluster.initial_master_nodes=es001,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - "rnet"
  es03:
    image: elasticsearch:8.2.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es001,es02
      - cluster.initial_master_nodes=es001,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - "rnet"

  kibana:
    image: kibana:8.2.0
    #    env_file:
    #      - env/tester-cluster.env
    networks:
      - "rnet"
    environment:
      ELASTICSEARCH_HOSTS: '["http://es001:9200","http://es02:9200","http://es03:9200"]'

    ports:
      - "5601:5601"
    #    restart: always
    depends_on:
      - es001
      - es02
      - es03

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  rnet:
    driver: bridge
    external: true
