version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:8.2.0
    container_name: es01
    environment:
      - discovery.type="single-node"
      - ELASTIC_PASSWORD=="elastic"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "rnet"

  kibana:
    image: kibana:8.2.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - elasticsearch.hosts=["http://es01:9200"]
    networks:
      - "rnet"


volumes:
  data01:
    driver: local

networks:
  rnet:
    driver: bridge
    external: true
