version: "3.7"
services:
  redis1:
    image: tticc/third:redis6.0.16
    ports:
      - "8881:8881"
      - "18881:18881"
    environment:
      - REDIS_PORT=8881
      - BIND=0.0.0.0
      - DATABASES=1
      - CLUSTER_ENABLED=yes
      - DAEMONIZE=no
    networks:
      - "rnet"

  redis2:
    image: tticc/third:redis6.0.16
    ports:
      - "8882:8882"
      - "18882:18882"
    environment:
      - REDIS_PORT=8882
      - BIND=0.0.0.0
      - DATABASES=1
      - CLUSTER_ENABLED=yes
      - DAEMONIZE=no
    networks:
      - "rnet"

  redis3:
    image: tticc/third:redis6.0.16
    ports:
      - "8883:8883"
      - "18883:18883"
    environment:
      - REDIS_PORT=8883
      - BIND=0.0.0.0
      - DATABASES=1
      - CLUSTER_ENABLED=yes
      - DAEMONIZE=no
    networks:
      - "rnet"

  redis4:
    image: tticc/third:redis6.0.16
    ports:
      - "8884:8884"
      - "18884:18884"
    environment:
      - REDIS_PORT=8884
      - BIND=0.0.0.0
      - DATABASES=1
      - CLUSTER_ENABLED=yes
      - DAEMONIZE=no
    networks:
      - "rnet"

  redis5:
    image: tticc/third:redis6.0.16
    ports:
      - "8885:8885"
      - "18885:18885"
    environment:
      - REDIS_PORT=8885
      - BIND=0.0.0.0
      - DATABASES=1
      - CLUSTER_ENABLED=yes
      - DAEMONIZE=no
    networks:
      - "rnet"

  redis6:
    image: tticc/third:redis6.0.16
    ports:
      - "8886:8886"
      - "18886:18886"
    environment:
      - REDIS_PORT=8886
      - BIND=0.0.0.0
      - DATABASES=1
      - CLUSTER_ENABLED=yes
      - DAEMONIZE=no
    networks:
      - "rnet"

networks:
  rnet:
    driver: bridge
    external: true



















