package com.tester.testerswing.swing;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

/**
 * @Author 温昌营
 * @Date 2022-8-5 15:55:52
 */
@Data
public class Sai_Input {
    private JPanel sai_input_panel;
    private JLabel sai_open_p1_label;
    private JTextField sai_open_p1_input;
    private JLabel sai_open_p2_label;
    private JTextField sai_open_p2_input;
    private JLabel sai_return_p1_label;
    private JTextField sai_return_p1_input;
    private JLabel sai_return_p2_label;
    private JTextField sai_return_p2_input;
    private JLabel sai_align_p1_label;
    private JLabel sai_align_p2_label;
    private JLabel sai_align_p3_label;
    private JTextField sai_align_p1_input;
    private JTextField sai_align_p2_input;
    private JTextField sai_align_p3_input;
    private JLabel sai_main_view_label;
    private JTextField sai_main_view_input;
    private JLabel sai_return_p3_label;
    private JTextField sai_return_p3_input;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:noGrow", "center:d:noGrow"));
        panel1.setEnabled(true);
        panel1.putClientProperty("html.disable", Boolean.FALSE);
        sai_input_panel = new JPanel();
        sai_input_panel.setLayout(new FormLayout("fill:45px:noGrow,left:0dlu:noGrow,fill:max(d;0px):noGrow,left:0dlu:noGrow,fill:90px:noGrow,left:4dlu:noGrow,fill:45px:noGrow,fill:90px:noGrow,left:4dlu:noGrow,fill:45px:noGrow,fill:90px:noGrow", "center:max(d;0px):noGrow,center:max(d;6px):noGrow,top:10dlu:noGrow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        panel1.add(sai_input_panel, cc.xy(1, 1));
        sai_open_p1_label = new JLabel();
        sai_open_p1_label.setText("打开1");
        sai_input_panel.add(sai_open_p1_label, new CellConstraints(1, 5, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_open_p1_input = new JTextField();
        sai_open_p1_input.setText("");
        sai_input_panel.add(sai_open_p1_input, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        sai_open_p2_label = new JLabel();
        sai_open_p2_label.setText("打开2");
        sai_input_panel.add(sai_open_p2_label, new CellConstraints(7, 5, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_open_p2_input = new JTextField();
        sai_open_p2_input.setText("");
        sai_input_panel.add(sai_open_p2_input, cc.xy(8, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        sai_return_p1_label = new JLabel();
        sai_return_p1_label.setText("回收1");
        sai_input_panel.add(sai_return_p1_label, new CellConstraints(1, 7, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_return_p1_input = new JTextField();
        sai_return_p1_input.setText("");
        sai_input_panel.add(sai_return_p1_input, cc.xy(5, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        sai_return_p2_label = new JLabel();
        sai_return_p2_label.setText("回收2");
        sai_input_panel.add(sai_return_p2_label, new CellConstraints(7, 7, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_return_p2_input = new JTextField();
        sai_return_p2_input.setText("");
        sai_input_panel.add(sai_return_p2_input, cc.xy(8, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        sai_align_p1_label = new JLabel();
        sai_align_p1_label.setText("朝向1");
        sai_input_panel.add(sai_align_p1_label, new CellConstraints(1, 9, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_align_p2_label = new JLabel();
        sai_align_p2_label.setText("朝向2");
        sai_input_panel.add(sai_align_p2_label, new CellConstraints(7, 9, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_align_p3_label = new JLabel();
        sai_align_p3_label.setText("朝向3");
        sai_input_panel.add(sai_align_p3_label, new CellConstraints(10, 9, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_align_p1_input = new JTextField();
        sai_align_p1_input.setText("");
        sai_input_panel.add(sai_align_p1_input, cc.xy(5, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        sai_align_p2_input = new JTextField();
        sai_align_p2_input.setText("");
        sai_input_panel.add(sai_align_p2_input, cc.xy(8, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        sai_align_p3_input = new JTextField();
        sai_align_p3_input.setText("");
        sai_input_panel.add(sai_align_p3_input, cc.xy(11, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        label1.setText("    Sai");
        sai_input_panel.add(label1, cc.xy(1, 3));
        sai_main_view_label = new JLabel();
        sai_main_view_label.setText("主览");
        sai_input_panel.add(sai_main_view_label, new CellConstraints(1, 11, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_main_view_input = new JTextField();
        sai_main_view_input.setText("");
        sai_input_panel.add(sai_main_view_input, cc.xy(5, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        sai_return_p3_label = new JLabel();
        sai_return_p3_label.setText("回收3");
        sai_input_panel.add(sai_return_p3_label, new CellConstraints(10, 7, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        sai_return_p3_input = new JTextField();
        sai_return_p3_input.setText("");
        sai_input_panel.add(sai_return_p3_input, cc.xy(11, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
    }
}
