package com.tester.testerswing.swing;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import lombok.Data;

import javax.swing.*;
import java.awt.*;

/**
 * @Author 温昌营
 * @Date 2022-8-5 15:55:58
 */
@Data
public class Silot_Input {
    private JLabel silot_open_p1_label;
    private JPanel silot_input_panel;
    private JTextField silot_open_p1_input;
    private JLabel silot_open_p2_label;
    private JTextField silot_open_p2_input;
    private JLabel silot_return_p1_label;
    private JTextField silot_return_p1_input;
    private JLabel silot_return_p12_label;
    private JTextField silot_return_p12_input;
    private JButton lead_shift_1;
    private JButton lead_shift_2;
    private JButton lead_shift_3;
    private JButton lead_shift_4;
    private JButton lead_shift_5;
    private JButton lead_shift_6;
    private JLabel leader_1;
    private JLabel leader_2;
    private JLabel leader_3;
    private JLabel leader_4;
    private JLabel leader_5;
    private JLabel leader_6;
    private JButton init_shift;
    private JButton around_trash1;
    private JButton around_trash2;
    private JButton around_trash3;
    private JButton around_trash4;
    private JButton around_trash5;
    private JButton around_trash6;
    private JLabel around_trash_status1;
    private JLabel around_trash_status2;
    private JLabel around_trash_status3;
    private JLabel around_trash_status4;
    private JLabel around_trash_status5;
    private JLabel around_trash_status6;
    private JButton init_trash;
    private JButton reduce_use;
    private JButton add_use;
    private JLabel accountNum2;
    private JLabel accountNum1;
    private JLabel hasGuard;
    private JButton use_guard;
    private JButton ban_guard;
    private JButton watch_capital;
    private JButton unwatch_capital;
    private JLabel isWatchingCapital;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        silot_input_panel = new JPanel();
        silot_input_panel.setLayout(new FormLayout("fill:45px:noGrow,left:0dlu:noGrow,fill:max(d;0px):noGrow,left:0dlu:noGrow,fill:90px:noGrow,left:4dlu:noGrow,fill:45px:noGrow,fill:90px:noGrow,left:4dlu:noGrow,fill:45px:noGrow,fill:90px:noGrow,left:50px:noGrow,fill:90px:noGrow,left:50px:noGrow,fill:90px:noGrow,left:50px:noGrow,fill:90px:noGrow", "center:max(d;0px):noGrow,center:max(d;6px):noGrow,top:10dlu:noGrow,top:4dlu:noGrow,center:d:noGrow,top:17px:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:17px:noGrow,center:24px:noGrow,top:20px:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:18px:noGrow,top:15px:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        silot_open_p1_label = new JLabel();
        silot_open_p1_label.setText("打开1");
        CellConstraints cc = new CellConstraints();
        silot_input_panel.add(silot_open_p1_label, new CellConstraints(1, 5, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        silot_open_p1_input = new JTextField();
        silot_open_p1_input.setText("");
        silot_input_panel.add(silot_open_p1_input, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        silot_open_p2_label = new JLabel();
        silot_open_p2_label.setText("打开2");
        silot_input_panel.add(silot_open_p2_label, new CellConstraints(7, 5, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        silot_open_p2_input = new JTextField();
        silot_open_p2_input.setText("");
        silot_input_panel.add(silot_open_p2_input, cc.xy(8, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        silot_return_p1_label = new JLabel();
        silot_return_p1_label.setText("收1.1");
        silot_input_panel.add(silot_return_p1_label, new CellConstraints(1, 7, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        silot_return_p1_input = new JTextField();
        silot_return_p1_input.setText("");
        silot_input_panel.add(silot_return_p1_input, cc.xy(5, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        label1.setText("    Silot");
        silot_input_panel.add(label1, cc.xy(1, 3));
        silot_return_p12_label = new JLabel();
        silot_return_p12_label.setText("收1.2");
        silot_input_panel.add(silot_return_p12_label, new CellConstraints(7, 7, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        silot_return_p12_input = new JTextField();
        silot_return_p12_input.setText("");
        silot_input_panel.add(silot_return_p12_input, cc.xy(8, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        lead_shift_1 = new JButton();
        lead_shift_1.setText("1_lead_shift");
        silot_input_panel.add(lead_shift_1, cc.xy(5, 17));
        lead_shift_2 = new JButton();
        lead_shift_2.setText("2_lead_shift");
        silot_input_panel.add(lead_shift_2, cc.xy(8, 17));
        lead_shift_3 = new JButton();
        lead_shift_3.setText("3_lead_shift");
        silot_input_panel.add(lead_shift_3, cc.xy(11, 17));
        lead_shift_4 = new JButton();
        lead_shift_4.setText("4_lead_shift");
        silot_input_panel.add(lead_shift_4, cc.xy(13, 17));
        lead_shift_5 = new JButton();
        lead_shift_5.setText("5_lead_shift");
        silot_input_panel.add(lead_shift_5, cc.xy(15, 17));
        leader_1 = new JLabel();
        leader_1.setText("Label");
        silot_input_panel.add(leader_1, cc.xy(5, 19, CellConstraints.CENTER, CellConstraints.DEFAULT));
        leader_2 = new JLabel();
        leader_2.setText("Label");
        silot_input_panel.add(leader_2, cc.xy(8, 19, CellConstraints.CENTER, CellConstraints.DEFAULT));
        leader_3 = new JLabel();
        leader_3.setText("Label");
        silot_input_panel.add(leader_3, cc.xy(11, 19, CellConstraints.CENTER, CellConstraints.DEFAULT));
        leader_4 = new JLabel();
        leader_4.setText("Label");
        silot_input_panel.add(leader_4, cc.xy(13, 19, CellConstraints.CENTER, CellConstraints.DEFAULT));
        leader_5 = new JLabel();
        leader_5.setText("Label");
        silot_input_panel.add(leader_5, cc.xy(15, 19, CellConstraints.CENTER, CellConstraints.DEFAULT));
        leader_6 = new JLabel();
        leader_6.setText("Label");
        silot_input_panel.add(leader_6, cc.xy(17, 19, CellConstraints.CENTER, CellConstraints.DEFAULT));
        init_shift = new JButton();
        init_shift.setText("init_leader");
        silot_input_panel.add(init_shift, cc.xy(11, 15));
        lead_shift_6 = new JButton();
        lead_shift_6.setText("6_lead_shift");
        silot_input_panel.add(lead_shift_6, cc.xy(17, 17));
        init_trash = new JButton();
        init_trash.setText("残骸init");
        silot_input_panel.add(init_trash, cc.xy(15, 15));
        around_trash1 = new JButton();
        around_trash1.setText("1残骸");
        silot_input_panel.add(around_trash1, cc.xy(5, 21));
        around_trash2 = new JButton();
        around_trash2.setText("2残骸");
        silot_input_panel.add(around_trash2, cc.xy(8, 21));
        around_trash3 = new JButton();
        around_trash3.setText("3残骸");
        silot_input_panel.add(around_trash3, cc.xy(11, 21));
        around_trash4 = new JButton();
        around_trash4.setText("4残骸");
        silot_input_panel.add(around_trash4, cc.xy(13, 21));
        around_trash5 = new JButton();
        around_trash5.setText("5残骸");
        silot_input_panel.add(around_trash5, cc.xy(15, 21));
        around_trash6 = new JButton();
        around_trash6.setText("6残骸");
        silot_input_panel.add(around_trash6, cc.xy(17, 21));
        around_trash_status1 = new JLabel();
        around_trash_status1.setText("Label");
        silot_input_panel.add(around_trash_status1, cc.xy(5, 23, CellConstraints.CENTER, CellConstraints.DEFAULT));
        around_trash_status2 = new JLabel();
        around_trash_status2.setText("Label");
        silot_input_panel.add(around_trash_status2, cc.xy(8, 23, CellConstraints.CENTER, CellConstraints.DEFAULT));
        around_trash_status3 = new JLabel();
        around_trash_status3.setText("Label");
        silot_input_panel.add(around_trash_status3, cc.xy(11, 23, CellConstraints.CENTER, CellConstraints.DEFAULT));
        around_trash_status4 = new JLabel();
        around_trash_status4.setText("Label");
        silot_input_panel.add(around_trash_status4, cc.xy(13, 23, CellConstraints.CENTER, CellConstraints.DEFAULT));
        around_trash_status5 = new JLabel();
        around_trash_status5.setText("Label");
        silot_input_panel.add(around_trash_status5, cc.xy(15, 23, CellConstraints.CENTER, CellConstraints.DEFAULT));
        around_trash_status6 = new JLabel();
        around_trash_status6.setText("Label");
        silot_input_panel.add(around_trash_status6, cc.xy(17, 23, CellConstraints.CENTER, CellConstraints.DEFAULT));
        reduce_use = new JButton();
        reduce_use.setText("reduce_use");
        silot_input_panel.add(reduce_use, cc.xy(5, 11));
        add_use = new JButton();
        add_use.setText("add_use");
        silot_input_panel.add(add_use, cc.xy(8, 11));
        accountNum2 = new JLabel();
        accountNum2.setText("Label");
        silot_input_panel.add(accountNum2, cc.xy(8, 13, CellConstraints.CENTER, CellConstraints.DEFAULT));
        accountNum1 = new JLabel();
        accountNum1.setText("Label");
        silot_input_panel.add(accountNum1, cc.xy(5, 13, CellConstraints.CENTER, CellConstraints.DEFAULT));
        ban_guard = new JButton();
        ban_guard.setText("禁用警卫");
        silot_input_panel.add(ban_guard, cc.xy(11, 11));
        use_guard = new JButton();
        use_guard.setText("启用警卫");
        silot_input_panel.add(use_guard, cc.xy(11, 9));
        hasGuard = new JLabel();
        hasGuard.setText("Label");
        silot_input_panel.add(hasGuard, cc.xy(11, 13, CellConstraints.CENTER, CellConstraints.DEFAULT));
        watch_capital = new JButton();
        watch_capital.setText("监控旗舰");
        silot_input_panel.add(watch_capital, cc.xy(13, 9));
        unwatch_capital = new JButton();
        unwatch_capital.setText("忽略旗舰");
        silot_input_panel.add(unwatch_capital, cc.xy(13, 11));
        isWatchingCapital = new JLabel();
        isWatchingCapital.setText("Label");
        silot_input_panel.add(isWatchingCapital, cc.xy(13, 13, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return silot_input_panel;
    }

}
